"""Charge sheet / case report generation as PDF."""

import io
from datetime import datetime, timezone
from typing import Any, Dict, List

from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import ListFlowable, ListItem, Paragraph, SimpleDocTemplate, Spacer

from ..models.case import Case
from . import legal_service


def _styles() -> Dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("title", parent=base["Title"], alignment=TA_CENTER, fontSize=16),
        "heading": ParagraphStyle("heading", parent=base["Heading2"], fontSize=12, spaceBefore=10),
        "body": ParagraphStyle("body", parent=base["BodyText"], fontSize=10, leading=14),
    }


def build_charge_sheet(case: Case, analyses: List[Dict[str, Any]] | None = None) -> bytes:
    styles = _styles()
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        title=f"Charge Sheet {case.case_number}",
    )

    story: List[Any] = [
        Paragraph("CHARGE SHEET", styles["title"]),
        Paragraph("Cyber Crime Branch", styles["title"]),
        Spacer(1, 10),
    ]

    details = [
        ("Case Number", case.case_number),
        ("Title", case.title),
        ("Crime Type", case.crime_type.replace("_", " ").title()),
        ("Status", case.status.replace("_", " ").title()),
        ("Priority", case.priority.title()),
        ("Complainant", case.complainant_name or "-"),
        ("Contact", case.complainant_contact or "-"),
        ("Location", case.location or "-"),
        ("Reported Loss", f"INR {case.loss_amount:,}"),
        ("Registered On", case.created_at.strftime("%d %b %Y")),
    ]
    story.append(Paragraph("1. Case Particulars", styles["heading"]))
    for label, value in details:
        story.append(Paragraph(f"<b>{label}:</b> {value}", styles["body"]))

    story.append(Paragraph("2. Brief Facts", styles["heading"]))
    story.append(Paragraph(case.description or "Not recorded.", styles["body"]))

    story.append(Paragraph("3. Sections Invoked", styles["heading"]))
    sections = legal_service.recommend_sections(case.crime_type, case.description or "")
    story.append(
        ListFlowable(
            [
                ListItem(
                    Paragraph(
                        f"{item['act']} Section {item['section']} - {item['title']} "
                        f"(confidence {item['confidence']}%)",
                        styles["body"],
                    )
                )
                for item in sections
            ],
            bulletType="bullet",
        )
    )

    story.append(Paragraph("4. Evidence Checklist", styles["heading"]))
    story.append(
        ListFlowable(
            [
                ListItem(Paragraph(item, styles["body"]))
                for item in legal_service.evidence_checklist(case.crime_type)
            ],
            bulletType="bullet",
        )
    )

    if analyses:
        story.append(Paragraph("5. AI Analysis Findings", styles["heading"]))
        for analysis in analyses:
            story.append(Paragraph(analysis.get("summary", ""), styles["body"]))
            for recommendation in analysis.get("recommendations", []):
                story.append(Paragraph(f"- {recommendation}", styles["body"]))
            story.append(Spacer(1, 6))

    story.append(Spacer(1, 16))
    story.append(
        Paragraph(
            f"Generated by CrimeGPT on {datetime.now(timezone.utc).strftime('%d %b %Y %H:%M UTC')}. "
            "This is an AI-assisted draft and must be verified by the investigating officer.",
            styles["body"],
        )
    )

    doc.build(story)
    return buffer.getvalue()
